FROM lambci/lambda:build-python3.8

RUN pip install -U pip-tools && \
  pip install -U zappa

RUN virtualenv /venv

RUN mkdir /var/task/app
COPY ./app /var/task/app

COPY ./aws.env /

RUN source /venv/bin/activate && \
    pip install -r /var/task/app/requirements.txt && \
    deactivate

WORKDIR /var/task/app